### ISSUE TITLE
Namespace for profiles ontology (and other things?)

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#503] opened 2018-10-26 11:23 UTC
Pinging @nicholascar and @draggett to discuss here.

Note: suggestion that came up at lunch: /dx/

**Comment by agbeltran** [comment] 2018-10-26 11:28
duplicate of https://github.com/w3c/dxwg/issues/398

**Comment by andrea-perego** [comment] 2021-02-19 14:15
> duplicate of #398

Can we then close this issue?

**Comment by andrea-perego** [comment] 2021-03-13 15:11
> > duplicate of #398
> 
> Can we then close this issue?

Noting no objections, I am closing this issue.

**Closed as completed by andrea-perego** 2021-03-13 15:11 UTC
Labels: due for closing
