### ISSUE TITLE
DCAT - ISO 19115 alignment (profile)

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#151] opened 2018-03-07 03:55 UTC
Prepare a formal alignment of DCAT to ISO 19115 (Geospatial metadata)

**Comment by andrea-perego** [comment] 2018-03-17 00:49
@dr-shorthair , I wonder which formal language we could use for aligning with DCAT non-RDF vocabularies.

For GeoDCAT-AP, this has been done by using XSLT. Should we go this way?

**Comment by nicholascar** [comment] 2018-03-17 12:55
There is a semi-official OWL interpretation of ISO19115 (https://github.com/ISO-TC211/GOM/tree/master/isotc211_GOM_harmonizedOntology/19115-1/2014) that we could use to show alignment however it's not very good in that the OWL was auto-created from UML XML files and doesn't follow best practice OWL modelling. We could still use that version to describe alignment though precisely because it is a direct UML (the standard) to OWL conversion.

**Comment by dr-shorthair** [comment] 2018-03-18 08:45
ISO 19150-2 defines the UML->OWL conversion rule. 
As part of the rule it prescribes URIs for all classes and properties, which can be considered 'official' as far as ISO/TC 211 is concerned. 

So in the SSN vocabulary we used the ISO 19156 O&M to support an axiomatization of the alignment or crosswalk - see https://www.w3.org/TR/vocab-ssn/#OM_Alignment 

(I also have my doubts about the quality of the OWL encoding, but that should not prevent us from using these URIs as a convenient shorthand for the elements of the UML model, which is the canonical representation.)

**Comment by dr-shorthair** [comment] 2018-03-18 08:51
Nevertheless, since the XML encoding is used as the reference by many installations it would make sense to provide a pathway. However, if heading that direction you'll probably need to consider 10139, 19139-2, 19115-3 ... I haven't kept up with the progress there so I don't know if they vary much.

**Comment by nicholascar** [comment] 2018-03-18 14:18
Why? Do we really think any XML-only 19115 users will want to see DCAT in XML?

I suggest that 19115 users interested in the future and DCAT and Semantic Web generally will be happy with a DCAT to OWL  19115 mapping as they will be mentally or technically mapping their ISO UML to OWL.

**Comment by smrgeoinfo** [comment] 2018-11-16 20:57
Actually, having a reviewed set of xpaths for mapping from ISO19139 and ISO19115-3 XML to DCAT would be very useful.  I haven't gotten around to building the xslt for the transform yet, but have done [ISO19139 to Schema.org,](https://github.com/usgin/metadataTransforms/blob/master/ISO19139toHTMLandSDO/ISO19139ToSchemaOrgDataset1.0.xslt) [DataCitev4 to Schema.org](https://github.com/usgin/metadataTransforms/blob/master/DataCiteToSchemaOrgDataset1.0.xslt), and [qualifiedDC to ISO19139](https://github.com/usgin/metadataTransforms/blob/master/qualifiedDCToISO19139v1.0.xslt).  Like @dr-shorthair I have reservations about the automated (ISO19150-2) UML to OWL generated ISO and don't see much uptake for that.  I think the collections of vocabularies being developed by dxwg are a better bet to replace ISO19139 in the rdf world; that's why I'd like to keep things conceptually in sync.

**Comment by andrea-perego** [comment] 2018-11-16 21:05
@smrgeoinfo , the GeoDCAT-AP XSLT is here:

https://github.com/SEMICeu/iso-19139-to-dcat-ap

**Comment by nicholascar** [comment] 2018-11-27 22:39
I will soon (by March) need to develop a DCAT-to-ISO19115-3 mapping for clients. I expect to use a Python script to query an [rdflib module](https://pypi.org/project/rdflib/), in-memory graph of a DCAT document and then to render ISO XML using Jinja2 templating. This is due to the client already using lots of rdflib and [Jinja2](http://jinja.pocoo.org/) and not wanting to use XSLT.

This work might be of wider interest, for instance it would be able to be placed on top of - an extension to - the [CKAN DCAT module](https://github.com/ckan/ckanext-dcat) (updated for DCAT revised of course) and export ISO19115-3 from there.

**Comment by nicholascar** [comment] 2018-12-06 06:54
I can confirm that I have a requirement for a March delivery here: one govt agency will use CKAN to store DCAT rev records and will then need to transform those to (a profile of) ISO19115-3 for consumption by another agency.

**Comment by dr-shorthair** [comment] 2021-02-24 01:18
@andrea-perego is the update of GeoDCAT complete?

**Comment by andrea-perego** [comment] 2021-02-24 10:17
@dr-shorthair asked:

> @andrea-perego is the update of GeoDCAT complete?

Yep. The new version of GeoDCAT-AP is aligned with DCAT 2:

https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/

**Comment by dr-shorthair** [comment] 2021-02-24 10:57
So I think that means that this ticket is now superseded, and can be closed, right?

**Comment by andrea-perego** [comment] 2021-02-24 11:02
+1 from me.

**Comment by andrea-perego** [comment] 2021-03-01 08:37
Noting no objections, I am closing this issue.

**Closed as completed by andrea-perego** 2021-03-01 08:37 UTC
Labels: dcat, alignment, due for closing
