### ISSUE TITLE
DCAT2.ttl: Request for minor changes

### ISSUE THREAD

**Issue by aidig** [w3c/dxwg#1246] opened 2020-08-12 08:24 UTC
1) Regarding the labels of properties such as dcat:dataset, dcat:distribution og dcat:catalog, it would be beneficial to prefer labels which highlight that the fact that these elements are properties and not classes by preferring labels such as “has dataset”, "has service", “has catalog” or “has distribution”. Currently, they differ only by way of capitalization. (also in normative spec)

2) Regarding the definition of dcat:Catalog, it would be more appropriate to move the examples to a comment or scopeNote. (also in normative spec)

3) The links provided in the scopeNote of dcat:Role and dcat:hadRole are unstable test addresses:  http://registry.it.csiro.au/def/isotc211/CI_RoleCode.& http://registry.it.csiro.au/def/isotc211/DS_AssociationTypeCode; The following is considered the correct url: https://def.isotc211.org/ontologies/iso19115/-1/2018/CitationAndResponsiblePartyInformation.rdf 

4) Regarding property dcat:spatialResolutionInMeters, it would be beneficial to add the following information from the DCAT spec (from bbox) in the TTL section describing dcat:spatialResolutionsInMeters or - ideally - replacing the current second scopeNote with this text: “The ability of to detect details in an raster image or grid is referred to as spatial resolution. The spatial resolution is stated in metres. The more pixels are included in a raster image of a certain area, the higher the spatial resolution meaning the more details can be observed”. 
(source: http://fis.uni-bonn.de/en/recherchetools/infobox/professionals/resolution/spatial-resolution)

**Comment by andrea-perego** [comment] 2021-03-25 23:36
Dear @aidig ,

Many apologies for replying so late.

You points 1 & 2 are being addressed in PR https://github.com/w3c/dxwg/pull/1337

About point 3, this issue is under discussion in https://github.com/w3c/dxwg/issues/975 , and we have yet to take a decision.

About point 4:

> 4. Regarding property dcat:spatialResolutionInMeters, it would be beneficial to add the following information from the DCAT spec (from bbox) in the TTL section describing dcat:spatialResolutionsInMeters or - ideally - replacing the current second scopeNote with this text: “The ability of to detect details in an raster image or grid is referred to as spatial resolution. The spatial resolution is stated in metres. The more pixels are included in a raster image of a certain area, the higher the spatial resolution meaning the more details can be observed”.
(source: http://fis.uni-bonn.de/en/recherchetools/infobox/professionals/resolution/spatial-resolution)

I'm not sure about this sentence:

> Regarding property dcat:spatialResolutionInMeters, it would be beneficial to add the following information from the DCAT spec (from bbox) in the TTL section describing dcat:spatialResolutionsInMeters [...]

Exactly, which information from the spec should be added to the .ttl?

About the text you propose, the issue is that it is specifically about the notion of spatial resolution in the geospatial domain, whereas DCAT is meant to be domain-agnostic, and the classes and properties used in DCAT (spatial resolution included) are addressing requirements identified across domains. We can still add it as an example ("For instance, in geospatial data etc."), but maybe the text should be re-phrased to be comprehensible also to non-geospatial people (e.g., not everyone is familiar with the notions of grid / raster images).

**Comment by agbeltran** [comment] 2021-03-26 17:44
About the first point on the labels, I would prefer to keep the labels as they are but add a ```skos:altLabel``` with the ```has x``` labels. 

Actually, for some of the translations this as already been done, see:
https://github.com/w3c/dxwg/blob/be83b5cf4d2657cac23937a423158e6bae53177e/dcat/rdf/dcat2.ttl#L646

This would affect @riccardoAlbertoni 's PR (https://github.com/w3c/dxwg/pull/1337)

**Comment by andrea-perego** [comment] 2021-03-26 17:55
> About the first point on the labels, I would prefer to keep the labels as they are but add a `skos:altLabel` with the `has x` labels.

I agree. I think we'd better keep aligned the labels with DCAT and DCAT2 for the properties used in those specs.

**Comment by agbeltran** [comment] 2021-03-26 17:59
Following up from my previous comment - there are two aspects, the text of the specification and the RDF representation.
@aidig perhaps you can clarify, but my reading of your issue is that you were referring to the RDF representation rather than the spec when pointing out about the labels? Or were you referring to both?

I think that for the spec, it is clear when it refers to a class or a property, e.g. see https://w3c.github.io/dxwg/dcat/#Property:catalog_catalog

For the RDF, I can see the value of adding an alternative label (e.g. ```skos:Label "has catalog"```) but I think it is useful that the main label aligns to the actual property name (```rdfs:label "catalog"```).

**Comment by agbeltran** [comment] 2021-03-26 18:21
Just one more thing, as per the subject on the issue, @aidig was talking about DCAT2.ttl.

**Comment by riccardoAlbertoni** [comment] 2021-03-29 11:46
I think the `rdfs:label`(s) correspond to the property/class section's title in the DCAT 2 rec document. 
Thus changing the `rdfs:label`(s) in the turtle implies changing the rec as well. 

Some of the discussed solutions are summarized below. 

**Solution 1:** 
 PR #1337 implements the changes required by pt 1  (the update of `rdfs:label`(s)) and pt 2 (the change of `dcat:Catalog` definition) in the next release DCAT 3 and maintains the turtle and the DCAT 3 document consistent.  

**Solution 2:**
We add  'has X'  as `skos:altLabel` instead of `rdfs:label` in the DCAT 2 turtle (pt 1).  Adding `skos:altLabel`  won't raise any consistency concern because the `skos:altLabel`(s) are not directly mapped into the REC. It is also back-compatible with previous versions of DCAT.
We can't change definitions as required in pt 2, as we want to have definitions consistent between TTL and rec DCAT 2,  and  DCAT 2 is frozen.  

**Solution 3:** namely solution 2 applied on DCAT 3 instead of DCAT 2.
 I would consider implementing changes on DCAT 3 more consistent with the expected way the recommendation process work. Solution 3   allows to implements pt 2.
 
Perhaps, we should have a quick pool to check whether we might build a consensus.

I would vote for solution 3.

**Comment by andrea-perego** [comment] 2021-03-29 22:02
Thanks, @riccardoAlbertoni , for drafting these proposals.

Solution 3 is not completely clear to me. Anyway, I would vote for adding `skos:altLabel` to the DCAT3 TTL, and leave untouched all the rest - the DCAT2 TTL and the DCAT3 spec.

**Comment by agbeltran** [comment] 2021-03-30 08:23
As stated before, I'm in favour of what @andrea-perego suggests, which I think it is the same as solution 3:  adding ```skos:altLabel``` to DCAT 3 ttl , and leave untouched DCAT2 ttl and DCAT3 spec.

**Comment by riccardoAlbertoni** [comment] 2021-04-08 10:56
points 1 & 2 are now addressed in PR #1348

**Comment by andrea-perego** [comment] 2021-04-10 21:39
> points 1 & 2 are now addressed in PR #1348

@aidig , PR #1348 has been merged, so your points 1 & 2 are supposed to be addressed.

About point 3, the discussion is happening in https://github.com/w3c/dxwg/issues/975

About point 4, we replied in https://github.com/w3c/dxwg/issues/1246#issuecomment-807735420 , asking for clarifications.

We will wait a few more days for your feedback, before closing this issue.

**Comment by andrea-perego** [comment] 2021-04-17 21:06
> > points 1 & 2 are now addressed in PR #1348
> 
> @aidig , PR #1348 has been merged, so your points 1 & 2 are supposed to be addressed.
> 
> About point 3, the discussion is happening in #975
> 
> About point 4, we replied in [#1246 (comment)](https://github.com/w3c/dxwg/issues/1246#issuecomment-807735420) , asking for clarifications.
> 
> We will wait a few more days for your feedback, before closing this issue.

Closing.

**Closed as completed by andrea-perego** 2021-04-17 21:06 UTC
Labels: dcat, requires discussion, Editorial, due for closing, feedback
