### ISSUE TITLE
Updating Data Quality Vocabulary wrt updates in POE

### ISSUE THREAD

**Issue by aisaac** [w3c/dxwg#5] opened 2017-06-18 16:53 UTC
The Data Quality Vocabulary had an example making use of the W3C Permissions and Obligation Expression vocabulary, ODRL: https://www.w3.org/TR/vocab-dqv/#ExpressConformanceWithPolicy

There was discussion to confirm the impact of recent POE updates to this use of POE by DQV. The result is that the DQV Note should be updated as it now refers to deprecated POE patterns:
https://github.com/w3c/poe/issues/159

**Comment by andrea-perego** [comment] 2021-03-13 13:54
@aisaac , unless there are any actions to be taken, I propose to close this issue.

**Comment by aisaac** [comment] 2021-05-04 20:12
Just a note that @riccardoAlbertoni and @plehegar are discussing this at the moment, so no closing right now :-)

**Comment by riccardoAlbertoni** [comment] 2023-01-24 11:10
After some exchange with Philippe it seems that  there is no way to update the Note unless we move the Working Group Note to the DXWG. This seems an overkill.

I propose closing this.

**Comment by makxdekkers** [comment] 2023-01-24 16:29
This is unfortunate. The lack of a maintenance process for Notes leads to these specifications inevitably becoming stale. If there is no sensible way to update the Note, maybe there could be a warning on the specification that it is no longer maintained and that there may be conflicts with other specifications? 
In a way, I feel this is a very strong warning to ourselves that publishing Notes is something to be avoided. It now basically throws away all the work that was done to create DQV which is not nice for the people who put their time and effort in its development.

**Comment by riccardoAlbertoni** [comment] 2023-01-30 19:44
@makxdekkers, Adopting a system to manage errata would have eased the above problem.  This might be a lesson to consider in case we are going to prepare any other Working Notes.

The ODRL vocabulary has evolved since DQV was published, and the expression of ODRL constraints now requires the representation of left and right operands. For those specifically interested, Example 7 in the DQV article published in the semantic web journal provides a corrected example, http://semantic-web-journal.org/system/files/swj2079.pdf.

Correcting the issue directly in the working note would have been more visible. However, I do not think the problem is impactful enough to invalidate our past work. Also, considering that DQV is not in the current DXWG mandate, I agree that moving DQV under the DXWG seems overkill, at least considering the current context.

**Closed** 2023-02-13 21:57 UTC
Labels: dcat, ucr, quality, due for closing
