### ISSUE TITLE
Responses can conform to multiple, modular profiles (UC 5.3)

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#217] opened 2018-04-24 16:33 UTC

**Comment by rob-metalinkage** [comment] 2018-05-17 23:27
@kcoyle feels that this requirement is not sufficiently traceable to specific Use Cases.  On review I felt this was a fair comment, and have proposed a new use case to explicitly state the DCAT-AP concerns at a high level. https://github.com/w3c/dxwg/issues/238.

To resolve we should: 1) refine and accept the UC 
2) back link this requirement to the new UC and others implicated.

Possibly the sub-requirements accepted as part of 6.8.2 Profile representation [RPFRP]  should be separated out into individual requirements and voted on systematically to verify that consensus is achieved, and concerns about specific aspects can be isolated and discussed on their merits. (Procedurally do we need to revisit this requirement with a proposal to revoke previous consensus acceptance and a new proposal to accept all the reworked sub-requirements for discussion ? Logically this would seem to need to be injected into the workplan for resolution before we could get back to solutions )

**Comment by kcoyle** [comment] 2018-05-18 06:39
@rob-metalinkage At the F2F Jaroslav and I took on the action to revisit the use cases that inform profile representation and derive requirements specific to each UC. I have started that <a href="https://docs.google.com/document/d/13hV2tJ6Kg2Hfe7e1BowY5QfCIweH9GxSCFQV1aWtOPg/edit#">in a G-Doc</a> and will try to have something in email to group by start of (the various) day(s) Monday. We should also gather the proposed new Use Cases (there are a few) and decide if we accept them into our work.

**Comment by rob-metalinkage** [comment] 2018-05-30 02:55
Effectively a duplicate of https://github.com/w3c/dxwg/issues/212

**Comment by azaroth42** [comment] 2018-06-21 21:53
I disagree that this is a duplicate of #212, as far as I understand the two. That one is about the composition of profiles, this one is about the application of profiles to data instances. The implications of this issue is that the relationship between instance (as carried in the http response body) and profile is many to many, not many to one. Thus the design of the HTTP response header that conveys the profile**s** supported must allow multiple values.

**Comment by kcoyle** [comment] 2018-06-21 22:40
There's more discussion of this at https://docs.google.com/document/d/13hV2tJ6Kg2Hfe7e1BowY5QfCIweH9GxSCFQV1aWtOPg/edit#heading=h.pgizj2q0xbuh . This is a use case written by Ruben and there has been quite a bit of discussion about what "modular" means. I don't think there's disagreement about multiple values, the question is whether profiles can consist of individual modules that are served during conneg (see the example given in the UC).

**Comment by aisaac** [comment] 2018-10-25 07:26
This is a duplicate of #287 and should be removed

**Closed as completed** 2019-05-02 12:49 UTC
Labels: requirement, profile-negotiation, profile-guidance, f2f3, due for closing
