### ISSUE TITLE
From SHACL: profiles based on same ontology

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#800] opened 2019-03-06 15:52 UTC
Comment in public comments list from Irene Polikoff:

> If two communities use two different profiles of the same base ontology, in order to understand how their data could interoperate, it would be important to be able to assess differences between these profiles. The examples above are all quite common, while at the same time very simple. One could easily list more complex examples. Is the goal of the working group is to provide means for addressing these issues?

https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jan/0001.html

**Comment by makxdekkers** [comment] 2019-03-07 08:42
I think these kinds of mapping approaches are outside of the scope of the PROF vocabulary.

**Comment by rob-metalinkage** [comment] 2019-03-07 20:29
out of scope except for the obvious mechanism of communities extending prof to define a specific role for a document or other resource that details differences between profiles. We cannot specify how such differences are described.  Profiles is only about statements of conformity, not about any other form of "closeness of information models" , but the support for inheritance hierarchies could help describe where two similar profiles diverge.

**Comment by kcoyle** [comment] 2019-03-08 00:46
@aisaac Does this relate to any of the uses you described in [ID37](https://w3c.github.io/dxwg/ucr/#ID37)? It looks to me like it could. It could still be out of scope, but we can acknowledge that we are aware of the use case, but aren't prepared to get to that level of detail in this version.

**Comment by nicholascar** [comment] 2019-08-22 11:45
This appears to be out-of-scope and no comments have come back here in several months so marking as both out-of-scope and due-for-closing.

**Comment by kcoyle** [comment] 2019-08-22 16:01
Because this came in as a public comment, there must be a response to the commenter on the public list, and the issue can only be closed when that commenter agrees with the solution.

**Comment by ghost** [comment] 2019-08-22 20:46
We will be contacting all those who have provided feedback on the public mailing list before closing.

**Comment by aisaac** [comment] 2019-08-26 08:18
@nicholascar that is fine but this seems not really matching the idea of 'due for closing' I would mark an issue such as the one here as 'due for closing' after an email has been sent, and we've received a reaction, or one month has passed and we got no reaction... This would be the idea of the label, for me.

@kcoyle @makxdekkers  all sorry I have not reacted because there are so many issues to react to, and I'm losing track. I guess I wanted to make progress on some other discussions first, and then this was on hold.
But I wouldn't consider it out of scope. Looking at how Karen formulated it, the issue is about enabling people to make a kind of diff between profiles of a same ontologies. It's not a mapping issue, in the sense that it doesn't require a formal alignment. One simply needs to understand differences between profiles. This is quite relevant, and indeed crucial to the vision of profile ecosystems (of which ID37 is only an example).
Now I would say we can't answer the need fully, and we should probably not seek to do it. Doing a full comparison would require to compare the "realizations/implementations" of the profiles, i.e. both the machine-readable specs (XML Schemas etc) or the human-readable ones. My take on this is that it is in scope for the formalisms these implementations are written in, not for us.
BUT we can still say that what's in scope for us is the first mile, i.e. the identification of the documents that shall be compared, so that one can answer the original question. And the serving of PROF descriptions of profiles is the tool for that. In informal terms it enables to say "You want to compare profiles? Well, if you want to do it, here are the various documents that you should compare to get your answer". It's not rocket science, but it's a key piece of the puzzle.

**Comment by aisaac** [comment] 2019-08-26 08:20
For the record I've searched for "Irene" in the whole DXWG comment list and it seems that we have never even acknowledged Irene's mail! And we have an issue for it? (the one here is only on a part of Irene's mail)

**Comment by rob-metalinkage** [comment] 2019-08-26 10:13
not a good look - consequence of getting "put on hold" :-(

**Comment by kcoyle** [comment] 2019-08-26 16:34
@aisaac At the last meeting I linked to [feedback issues that are still open for PROF](https://github.com/w3c/dxwg/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Afeedback+label%3A%22ON+HOLD+profiles-vocabulary%22). Although Rob says this is a consequence of being put on hold, these are feedback to the first public working draft, received in January, not the 2pwd that was issued as PROF was put on hold in April. So these are questions that should have been responded to in that interim between the two drafts. We need to catch up on them - the 2nd draft may have addressed them but no formal response was sent back to the commenters.

**Comment by aisaac** [comment] 2019-08-26 23:09
@kcoyle that list is very useful. I glanced at the minutes but as the link was not clearly introduced by text I thought it was a side discussion... But I guess we all agree we should acknowledge and reply (and looking at @rob-metalinkage 's reaction it seems he agrees too)

**Comment by rob-metalinkage** [comment] 2019-08-26 23:25
@aisaac - I like your way of expressing this and acknowledge that we could inject some wording to make this more explicit. I am surprised its neccesary - because its kind of obvious and is what happens everywhere we have a description of a thing, in that the things themselves need to be examined to discover relationships not explicitly described in the descriptions.  But the evidence is there that it needs to be stated.  This also needs to be in the guidance doc - so if you wanted to inject a clause there we could quote it in the explanation of the profiles vocabulary and usage notes.
(elsewhere you made the good point that the vocabulary should focus on just describing the model not how it is to be used in all cases)

**Comment by nicholascar** [comment] 2019-08-26 23:31
+1 to "the vocabulary should focus on just describing the model not how it is to be used in all cases"

Other W3C vocabs are like this: look at the length of documentation around [ADMS](https://www.w3.org/TR/vocab-adms/) and even the [original DCAT](https://www.w3.org/TR/vocab-dcat/) compared with the new DCAT documentation (and perhaps even the eventual PROF documentation).

**Comment by kcoyle** [comment] 2019-08-26 23:51
@aisaac Note that although I posted the issue, it is a comment from Irene Polikoff of SHACL. I'll make that clearer in the opening comment.

**Comment by nicholascar** [comment] 2019-09-03 14:38
A final comment on this issue unless we get further feedback from the proponent:

This sort of mechanics are though by the group to be out-of-scope for the Profiles Vocabulary as they would likely need to be community-specific to be implementable. Having said that, since the Vocabulary presents a set of Roles that can be extended, a community could extend that role list to suit their needs. They could implement a profiles-differences or a differences-form-base resource. A further though: communities could define profiles of the base that the profiles they wish to compare conform to. In this new profile that is intermediate between the base and the ones they are comparing, they could list all the elements that the profiles being compared have in common. This would narrow the task of interpreting their differences.

This comments has been forwarded to the Issue raiser, Irene Polikoff, via the DXWG public mailing list: https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Sep/0000.html.

**Comment by nicholascar** [comment] 2019-09-23 10:20
Closing after a period of due-for-closing and no further actions.

**Closed as completed by nicholascar** 2019-09-23 10:20 UTC
Labels: profile-guidance, out of scope, profiles-vocabulary, due for closing, feedback

**Comment by kcoyle** [comment] 2019-09-23 20:51
@nicholascar I see that we never heard back from Irene. It might be good to note that here. I don't think that changes the decision but we didn't get a positive agreement from the SHACL group, in spite of answering all of the questions.
